name: community_charts_flutter
version: 1.0.2
description: Material Design charting library for flutter. Forked from google/charts.
repository: https://github.com/juliansteenbakker/community_charts

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  collection: ">=0.14.5 <2.0.0"
  meta: ">=1.1.1 <2.0.0"
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of community_charts_flutter will point to the pub version of community_charts_common.
  # The latest pub version is commented out and shown below as an example.
  community_charts_common: ^1.0.2
#  community_charts_common:
#    path: ../community_charts_common/
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.3.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter