name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  community_charts_flutter:
    path: ../
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.1
  intl: ">=0.15.2 <0.19.0"
flutter:
  uses-material-design: true
