name: community_charts_common
version: 1.0.0
description: A common library for charting packages. Forked from google/charts.
repository: https://github.com/juliansteenbakker/community_charts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ">=0.17.0 <0.19.0"
  collection: ">=0.14.5 <2.0.0"
  meta: ">=1.1.1 <2.0.0"
  vector_math: ">=2.0.8 <3.0.0"

dev_dependencies:
  mockito: ^5.3.0
  test: ^1.22.0
