name: community_charts_common
version: 1.0.0
description: A common library for charting packages. Forked from google/charts.
homepage: https://github.com/juliansteenbakker/community_charts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.14.5
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.1.1
  vector_math: ^2.0.8

dev_dependencies:
  mockito: ^5.3.0
  test: ^1.22.0
